import 'dart:convert';
import 'dart:math';
import 'dart:typed_data';

import 'package:fixnum/fixnum.dart';
import 'package:hex/hex.dart';
import 'package:test/test.dart';

import 'package:redpanda_light_client/src/crypto/channel_message.dart';
import 'package:redpanda_light_client/src/crypto/group_control.dart';
import 'package:redpanda_light_client/src/domain/group_state.dart';
import 'package:redpanda_light_client/src/domain/reverse_garlic_block.dart';
import 'package:redpanda_light_client/src/garlic/garlic_builder.dart';
import 'package:redpanda_light_client/src/generated/client/channel_message.pb.dart'
    as cm_pb;
import 'package:redpanda_light_client/src/generated/client/group_control.pb.dart'
    as gc_pb;
import 'package:redpanda_light_client/src/generated/client/reverse_garlic_block.pb.dart'
    as rgb_pb;

/// TD098/T142: the client-to-client schemas under `protos/client/` must
/// describe exactly the bytes the original hand-written codecs put on the
/// wire.
///
/// This file was written against those hand encoders (redpanda-mobile
/// cf8f98d) and kept when the codec classes switched to the generated code:
/// for every message, the codec class's encoder == the generated message
/// built field by field from the same values, generated decode → re-encode
/// of its bytes is the identity, and its decoder reads the generated bytes
/// back. Checked on fixed, golden and seeded random vectors. The frozen
/// bytes of the hand encoders themselves are checked in
/// `legacy_wire_corpus_test.dart`.
///
/// protobuf-dart quirk this relies on: unlike canonical proto3, it writes a
/// scalar that was explicitly *set* even when it holds the default value
/// (`content = ''` becomes `1a 00`). The `*ToPb` builders below therefore set
/// only non-default values — the proto3 elision the hand encoders did and the
/// codec classes now do.
void main() {
  final rnd = Random(0x7142);

  Uint8List bytes(int n) =>
      Uint8List.fromList(List<int>.generate(n, (_) => rnd.nextInt(256)));
  String text(int n) => String.fromCharCodes(
    List<int>.generate(n, (_) {
      // Mix ASCII with multi-byte code points so UTF-8 lengths differ from
      // char counts.
      final pick = rnd.nextInt(10);
      if (pick < 7) return 0x20 + rnd.nextInt(0x5F);
      if (pick < 9) return 0xA0 + rnd.nextInt(0x700);
      return 0x4E00 + rnd.nextInt(0x1000);
    }),
  );
  // Lengths that cross the 1-byte/2-byte varint boundary at 128.
  int len() => const [0, 1, 16, 127, 128, 129, 300][rnd.nextInt(7)];
  Uint8List? maybe(Uint8List Function() f) => rnd.nextBool() ? f() : null;

  // ---------------------------------------------------------------- //
  // ChannelMessage
  // ---------------------------------------------------------------- //

  cm_pb.ChannelMessage toPb(ChannelMessage m) {
    final pb = cm_pb.ChannelMessage();
    if (m.messageId.isNotEmpty) pb.messageId = m.messageId;
    if (m.timestampMs != 0) pb.timestampMs = Int64(m.timestampMs);
    if (m.content.isNotEmpty) pb.content = m.content;
    if (m.replyPath?.isNotEmpty ?? false) pb.replyPath = m.replyPath!;
    if (m.ackMessageId?.isNotEmpty ?? false) pb.ackMessageId = m.ackMessageId!;
    if (m.groupHandshake?.isNotEmpty ?? false) {
      pb.groupHandshake = m.groupHandshake!;
    }
    if (m.groupControl?.isNotEmpty ?? false) pb.groupControl = m.groupControl!;
    if (m.ohUpdate?.isNotEmpty ?? false) pb.ohUpdate = m.ohUpdate!;
    return pb;
  }

  void expectSameFields(ChannelMessage a, ChannelMessage b) {
    expect(a.messageId, b.messageId);
    expect(a.timestampMs, b.timestampMs);
    expect(a.content, b.content);
    expect(a.replyPath ?? Uint8List(0), b.replyPath ?? Uint8List(0));
    expect(a.ackMessageId ?? Uint8List(0), b.ackMessageId ?? Uint8List(0));
    expect(a.groupHandshake ?? Uint8List(0), b.groupHandshake ?? Uint8List(0));
    expect(a.groupControl ?? Uint8List(0), b.groupControl ?? Uint8List(0));
    expect(a.ohUpdate ?? Uint8List(0), b.ohUpdate ?? Uint8List(0));
  }

  void checkChannelMessage(ChannelMessage m) {
    final hand = m.encode();
    expect(toPb(m).writeToBuffer(), hand, reason: 'generated encoder');
    final decoded = cm_pb.ChannelMessage.fromBuffer(hand);
    expect(decoded.writeToBuffer(), hand, reason: 'generated re-encode');
    expect(decoded.timestampMs.toInt(), m.timestampMs);
    expect(decoded.content, m.content);
    expectSameFields(ChannelMessage.decode(toPb(m).writeToBuffer()), m);
  }

  group('ChannelMessage schema', () {
    test('fixed vectors', () {
      final vectors = <ChannelMessage>[
        ChannelMessage(
          messageId: Uint8List.fromList(List<int>.generate(16, (i) => i)),
          timestampMs: 1765000000000,
          content: 'hello',
        ),
        ChannelMessage(messageId: Uint8List(0), timestampMs: 0, content: ''),
        // proto3 int64 negatives are 10-byte varints on both sides.
        ChannelMessage(
          messageId: Uint8List(16),
          timestampMs: -1,
          content: 'Grüße 👋',
        ),
        ChannelMessage(
          messageId: Uint8List(16),
          timestampMs: 1,
          content: 'x' * 200,
          replyPath: Uint8List.fromList(List<int>.filled(150, 7)),
          ackMessageId: Uint8List.fromList(List<int>.filled(16, 9)),
          groupHandshake: Uint8List.fromList([1, 2, 3]),
          groupControl: Uint8List.fromList([4, 5]),
          ohUpdate: Uint8List.fromList(utf8.encode('{"oh":1}')),
        ),
        // Empty optional fields stay off the wire in both encoders.
        ChannelMessage(
          messageId: Uint8List(16),
          timestampMs: 5,
          content: 'c',
          replyPath: Uint8List(0),
          ackMessageId: Uint8List(0),
          groupHandshake: Uint8List(0),
          groupControl: Uint8List(0),
          ohUpdate: Uint8List(0),
        ),
      ];
      vectors.forEach(checkChannelMessage);
    });

    test('golden bytes', () {
      expect(
        HEX.encode(
          ChannelMessage(
            messageId: Uint8List.fromList([1, 2, 3]),
            timestampMs: 300,
            content: 'hi',
            ackMessageId: Uint8List.fromList([0xAA]),
          ).encode(),
        ),
        '0a03010203'
        '10ac02'
        '1a026869'
        '3201aa',
      );
    });

    test('random cases', () {
      for (var i = 0; i < 400; i++) {
        final tsPick = rnd.nextInt(4);
        final ts = switch (tsPick) {
          0 => 0,
          1 => rnd.nextInt(1 << 32) * (1 << 12) + rnd.nextInt(1 << 12),
          2 => -rnd.nextInt(1 << 32) - 1,
          _ => rnd.nextInt(1 << 20),
        };
        checkChannelMessage(
          ChannelMessage(
            messageId: bytes(rnd.nextBool() ? 16 : len()),
            timestampMs: ts,
            content: text(len()),
            replyPath: maybe(() => bytes(len())),
            ackMessageId: maybe(() => bytes(len())),
            groupHandshake: maybe(() => bytes(len())),
            groupControl: maybe(() => bytes(len())),
            ohUpdate: maybe(() => bytes(len())),
          ),
        );
      }
    });
  });

  // ---------------------------------------------------------------- //
  // ReverseGarlicBlock
  // ---------------------------------------------------------------- //

  GarlicHop randomHop() =>
      GarlicHop(nodeId: bytes(20), encryptionPublicKey: bytes(32));

  rgb_pb.ReverseGarlicBlock rgbToPb(ReverseGarlicBlock b) =>
      rgb_pb.ReverseGarlicBlock(
        version: b.version,
        expiryTs: Int64(b.expiryTs),
        sessionTag: b.sessionTag,
        ohId: b.ohId,
        hops: [
          for (final h in b.hops)
            rgb_pb.RgbHop(kadId: h.nodeId, encPub: h.encryptionPublicKey),
        ],
      );

  void checkRgb(ReverseGarlicBlock b) {
    final hand = b.serialize();
    expect(rgbToPb(b).writeToBuffer(), hand, reason: 'generated encoder');
    final decoded = rgb_pb.ReverseGarlicBlock.fromBuffer(hand);
    expect(decoded.writeToBuffer(), hand, reason: 'generated re-encode');
    final back = ReverseGarlicBlock.deserialize(rgbToPb(b).writeToBuffer());
    expect(back.version, b.version);
    expect(back.expiryTs, b.expiryTs);
    expect(back.sessionTag, b.sessionTag);
    expect(back.ohId, b.ohId);
    expect(back.hops.map((h) => h.nodeId).toList(), [
      for (final h in b.hops) h.nodeId,
    ]);
    expect(back.hops.map((h) => h.encryptionPublicKey).toList(), [
      for (final h in b.hops) h.encryptionPublicKey,
    ]);
  }

  group('ReverseGarlicBlock schema', () {
    test('expiry_ts = 0 stays on the wire (explicit presence)', () {
      final b = ReverseGarlicBlock(
        expiryTs: 0,
        sessionTag: Uint8List(16),
        ohId: Uint8List(20),
        hops: [randomHop()],
      );
      expect(b.serialize().sublist(0, 4), [0x08, 0x01, 0x10, 0x00]);
      checkRgb(b);
    });

    test('golden bytes', () {
      final b = ReverseGarlicBlock(
        expiryTs: 1765000000000,
        sessionTag: List<int>.generate(16, (i) => i),
        ohId: List<int>.generate(20, (i) => 100 + i),
        hops: [
          GarlicHop(
            nodeId: List<int>.filled(20, 1),
            encryptionPublicKey: List<int>.filled(32, 2),
          ),
        ],
      );
      expect(
        HEX.encode(b.serialize()),
        '0801'
        '1080e4ca91af33'
        '1a10${HEX.encode(List<int>.generate(16, (i) => i))}'
        '2214${HEX.encode(List<int>.generate(20, (i) => 100 + i))}'
        '2a38'
        '0a14${'01' * 20}'
        '1220${'02' * 32}',
      );
      checkRgb(b);
    });

    test('random cases', () {
      for (var i = 0; i < 300; i++) {
        checkRgb(
          ReverseGarlicBlock(
            expiryTs: rnd.nextInt(4) == 0
                ? 0
                : rnd.nextInt(1 << 32) * (1 << 11) + rnd.nextInt(1 << 11),
            sessionTag: bytes(16),
            ohId: bytes(20),
            hops: List<GarlicHop>.generate(
              1 + rnd.nextInt(5),
              (_) => randomHop(),
            ),
          ),
        );
      }
    });
  });

  // ---------------------------------------------------------------- //
  // GroupControl / GroupHandshake
  // ---------------------------------------------------------------- //

  String hex(int n) => HEX.encode(bytes(n));

  GroupMemberInfo randomMember() => GroupMemberInfo(
    memberIdHex: hex(32),
    displayName: text(rnd.nextInt(3) == 0 ? 0 : 1 + rnd.nextInt(40)),
    ohId: rnd.nextBool() ? bytes(20) : null,
    ohEndpoint: switch (rnd.nextInt(3)) {
      0 => null,
      1 => '',
      _ => '10.0.${rnd.nextInt(256)}.${rnd.nextInt(256)}:59558',
    },
    x25519PubHex: hex(32),
    role: rnd.nextInt(2),
  );

  gc_pb.GroupMember memberToPb(GroupMemberInfo m) {
    final pb = gc_pb.GroupMember(
      memberId: HEX.decode(m.memberIdHex),
      x25519Pub: HEX.decode(m.x25519PubHex),
    );
    if (m.displayName.isNotEmpty) pb.displayName = m.displayName;
    if (m.ohId?.isNotEmpty ?? false) pb.ohId = m.ohId!;
    if (m.ohEndpoint?.isNotEmpty ?? false) pb.ohEndpoint = m.ohEndpoint!;
    if (m.role != 0) pb.role = m.role;
    return pb;
  }

  gc_pb.KeyRotation rotationToPb(KeyRotation r) {
    final pb = gc_pb.KeyRotation(
      groupSecret: r.groupSecret,
      keyEpoch: r.keyEpoch,
      members: r.members.map(memberToPb),
    );
    if (r.groupName.isNotEmpty) pb.groupName = r.groupName;
    return pb;
  }

  void expectSameMembers(List<GroupMemberInfo> a, List<GroupMemberInfo> b) {
    expect(a.length, b.length);
    for (var i = 0; i < a.length; i++) {
      expect(a[i].memberIdHex, b[i].memberIdHex);
      expect(a[i].displayName, b[i].displayName);
      expect(a[i].ohId, b[i].ohId);
      // The hand encoder drops an empty endpoint, so '' decodes as null.
      expect(a[i].ohEndpoint ?? '', b[i].ohEndpoint ?? '');
      expect(a[i].x25519PubHex, b[i].x25519PubHex);
      expect(a[i].role, b[i].role);
    }
  }

  void checkRotation(KeyRotation r) {
    final hand = GroupControl.rotation(r).encode();
    final pb = gc_pb.GroupControl(keyRotation: rotationToPb(r));
    expect(pb.writeToBuffer(), hand, reason: 'generated encoder');
    final decoded = gc_pb.GroupControl.fromBuffer(hand);
    expect(decoded.whichAction(), gc_pb.GroupControl_Action.keyRotation);
    expect(decoded.writeToBuffer(), hand, reason: 'generated re-encode');
    final back = GroupControl.decode(pb.writeToBuffer()).keyRotation!;
    expect(back.groupSecret, r.groupSecret);
    expect(back.keyEpoch, r.keyEpoch);
    expect(back.groupName, r.groupName);
    expectSameMembers(back.members, r.members);
  }

  void checkInfo(String name) {
    final hand = GroupControl.info(GroupInfoUpdate(name: name)).encode();
    final pb = gc_pb.GroupControl(
      infoUpdate: name.isEmpty ? null : gc_pb.GroupInfoUpdate(name: name),
    );
    expect(pb.writeToBuffer(), hand, reason: 'generated encoder');
    expect(gc_pb.GroupControl.fromBuffer(hand).writeToBuffer(), hand);
    expect(GroupControl.decode(pb.writeToBuffer()).infoUpdate!.name, name);
  }

  void checkHandshake(GroupHandshake h) {
    final hand = h.encode();
    final gc_pb.GroupHandshake pb;
    if (h.isProposal) {
      final proposal = gc_pb.InviteProposal(
        groupId: HEX.decode(h.proposalGroupIdHex!),
        adminMemberId: HEX.decode(h.proposalAdminMemberIdHex!),
      );
      if (h.proposalGroupName?.isNotEmpty ?? false) {
        proposal.groupName = h.proposalGroupName!;
      }
      pb = gc_pb.GroupHandshake(proposal: proposal);
    } else {
      final accept = gc_pb.JoinAccept(
        groupId: HEX.decode(h.acceptGroupIdHex!),
        memberId: HEX.decode(h.acceptMemberIdHex!),
        x25519Pub: HEX.decode(h.acceptX25519PubHex!),
        ohId: h.acceptOhId,
      );
      if (h.acceptOhEndpoint!.isNotEmpty) {
        accept.ohEndpoint = h.acceptOhEndpoint!;
      }
      pb = gc_pb.GroupHandshake(accept: accept);
    }
    expect(pb.writeToBuffer(), hand, reason: 'generated encoder');
    expect(gc_pb.GroupHandshake.fromBuffer(hand).writeToBuffer(), hand);
    final back = GroupHandshake.decode(pb.writeToBuffer());
    expect(back.isProposal, h.isProposal);
    expect(back.proposalGroupIdHex, h.proposalGroupIdHex);
    expect(back.proposalGroupName, h.proposalGroupName);
    expect(back.proposalAdminMemberIdHex, h.proposalAdminMemberIdHex);
    expect(back.acceptGroupIdHex, h.acceptGroupIdHex);
    expect(back.acceptMemberIdHex, h.acceptMemberIdHex);
    expect(back.acceptX25519PubHex, h.acceptX25519PubHex);
    expect(back.acceptOhId, h.acceptOhId);
    expect(back.acceptOhEndpoint, h.acceptOhEndpoint);
  }

  group('GroupControl schema', () {
    test('golden bytes: admin role (0) is omitted, member role is not', () {
      final admin = GroupMemberInfo(
        memberIdHex: '11' * 32,
        displayName: 'A',
        x25519PubHex: '22' * 32,
        role: GroupMemberInfo.roleAdmin,
      );
      final member = GroupMemberInfo(
        memberIdHex: '33' * 32,
        displayName: '',
        ohId: List<int>.filled(20, 0x44),
        ohEndpoint: 'h:1',
        x25519PubHex: '55' * 32,
        role: GroupMemberInfo.roleMember,
      );
      final rotation = KeyRotation(
        groupSecret: Uint8List.fromList(List<int>.filled(32, 0x66)),
        keyEpoch: 2,
        members: [admin, member],
        groupName: 'G',
      );
      final adminBytes =
          '0a20${'11' * 32}'
          '120141'
          '2a20${'22' * 32}';
      final memberBytes =
          '0a20${'33' * 32}'
          '1a14${'44' * 20}'
          '2203683a31'
          '2a20${'55' * 32}'
          '3001';
      // Encoded lengths: admin 71 (0x47), member 97 (0x61), rotation 211.
      final rotationBytes =
          '0a20${'66' * 32}'
          '1002'
          '1a47$adminBytes'
          '1a61$memberBytes'
          '220147';
      expect(
        HEX.encode(GroupControl.rotation(rotation).encode()),
        '0ad301$rotationBytes',
      );
      checkRotation(rotation);
    });

    test('random rotations', () {
      for (var i = 0; i < 200; i++) {
        checkRotation(
          KeyRotation(
            groupSecret: bytes(32),
            keyEpoch: rnd.nextBool()
                ? 1 + rnd.nextInt(1000)
                : 1 + rnd.nextInt(0xFFFFFFFF),
            members: List<GroupMemberInfo>.generate(
              rnd.nextInt(6),
              (_) => randomMember(),
            ),
            groupName: text(rnd.nextInt(3) == 0 ? 0 : len()),
          ),
        );
      }
    });

    test('info updates', () {
      checkInfo('Neuer Name');
      for (var i = 0; i < 100; i++) {
        checkInfo(text(1 + rnd.nextInt(200)));
      }
    });

    test('known divergence: an empty rename is not proto3-identical', () {
      // The hand encoder drops an empty GroupInfoUpdate entirely (and the
      // receiver then rejects "no action set"), while proto3 writes a set
      // oneof member even when it is empty. A generated-codec replacement
      // must therefore leave the oneof unset for an empty name to keep the
      // wire bytes unchanged.
      expect(
        GroupControl.info(const GroupInfoUpdate(name: '')).encode(),
        isEmpty,
      );
      expect(
        gc_pb.GroupControl(infoUpdate: gc_pb.GroupInfoUpdate()).writeToBuffer(),
        [0x12, 0x00],
      );
    });

    test('handshakes', () {
      checkHandshake(
        GroupHandshake.proposal(
          groupIdHex: '01' * 32,
          groupName: '',
          adminMemberIdHex: '02' * 32,
        ),
      );
      for (var i = 0; i < 200; i++) {
        checkHandshake(
          rnd.nextBool()
              ? GroupHandshake.proposal(
                  groupIdHex: hex(32),
                  groupName: text(len()),
                  adminMemberIdHex: hex(32),
                )
              : GroupHandshake.accept(
                  groupIdHex: hex(32),
                  memberIdHex: hex(32),
                  x25519PubHex: hex(32),
                  ohId: bytes(20),
                  ohEndpoint: rnd.nextBool() ? '' : 'node.example:59558',
                ),
        );
      }
    });
  });
}
