#!/usr/bin/env python3
"""update_map.py – Generates / updates the persistent project map.

Usage:
    python .agent-skills/repo-mapper/scripts/update_map.py [project_root]

If *project_root* is omitted, the current working directory is used.

The script walks the project tree (respecting ignore patterns) and writes
one ``_index.md`` file per directory into the ``map/`` folder inside the
repo-mapper skill directory.  Each ``_index.md`` lists the subdirectories
and files of the corresponding project directory so that an agent can
navigate the map by reading these small Markdown files.
"""

import os
import shutil
import sys
from datetime import datetime, timezone

# ── configuration ────────────────────────────────────────────────────────────

IGNORED_DIRS = {
    ".git",
    "node_modules",
    "venv",
    ".venv",
    "__pycache__",
    "dist",
    "build",
    ".idea",
    ".dart_tool",
    ".pub-cache",
    ".pub",
}

# Path to the map directory **relative to the project root**.
SKILL_DIR = os.path.join(".agent-skills", "repo-mapper")
MAP_DIR = os.path.join(SKILL_DIR, "map")

# ── helpers ──────────────────────────────────────────────────────────────────


def _should_ignore(name: str) -> bool:
    """Return True if a directory entry should be skipped."""
    return name in IGNORED_DIRS


def _write_index(map_path: str, rel_dir: str, dirs: list[str], files: list[str]) -> None:
    """Write an ``_index.md`` for *rel_dir* into the map tree."""
    os.makedirs(map_path, exist_ok=True)
    index_path = os.path.join(map_path, "_index.md")

    display_dir = rel_dir if rel_dir != "." else "(root)"

    lines: list[str] = []
    lines.append(f"# 📂 `{display_dir}/`\n")
    lines.append(
        f"> Auto-generated by `update_map.py` — "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n"
    )

    if dirs:
        lines.append("## Unterordner\n")
        for d in sorted(dirs):
            sub_rel = os.path.join(rel_dir, d) if rel_dir != "." else d
            map_link = os.path.join(d, "_index.md")
            lines.append(f"* 📁 [{d}/]({map_link})")
        lines.append("")

    if files:
        lines.append("## Dateien\n")
        for f in sorted(files):
            file_rel = os.path.join(rel_dir, f) if rel_dir != "." else f
            lines.append(f"* 📄 `{f}`")
        lines.append("")

    if not dirs and not files:
        lines.append("*(leerer Ordner)*\n")

    with open(index_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


# ── main logic ───────────────────────────────────────────────────────────────


def generate_map(project_root: str) -> None:
    """Walk *project_root* and create the map tree under ``MAP_DIR``."""
    project_root = os.path.normpath(project_root)

    if not os.path.isdir(project_root):
        print(f"Error: '{project_root}' is not a valid directory.")
        sys.exit(1)

    abs_map_dir = os.path.join(project_root, MAP_DIR)

    # Remove stale map so deleted dirs/files are not left behind.
    if os.path.isdir(abs_map_dir):
        shutil.rmtree(abs_map_dir)

    # Also skip the skill directory itself to avoid recursion.
    skill_abs = os.path.normpath(os.path.join(project_root, SKILL_DIR))

    for dirpath, dirnames, filenames in os.walk(project_root):
        # Skip ignored directories (modifying dirnames in-place prunes walk).
        dirnames[:] = [
            d
            for d in dirnames
            if not _should_ignore(d)
            and os.path.normpath(os.path.join(dirpath, d)) != skill_abs
        ]
        dirnames.sort()

        # Hide hidden files (dotfiles) except at root level.
        rel_dir = os.path.relpath(dirpath, project_root)
        visible_files = [f for f in filenames if not f.startswith(".") or rel_dir == "."]
        visible_files.sort()

        # Determine corresponding map path.
        if rel_dir == ".":
            map_path = abs_map_dir
        else:
            map_path = os.path.join(abs_map_dir, rel_dir)

        _write_index(map_path, rel_dir, dirnames, visible_files)

    print(f"✅ Map updated at '{os.path.relpath(abs_map_dir, project_root)}/'")


if __name__ == "__main__":
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    generate_map(root)
